linters:
  enable:
    - asciicheck
    - bodyclose
<<<<<<< HEAD
    # - deadcode
=======
>>>>>>> 83b7f4ad5 (ci: Fix linter complaint (#9645))
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    - goconst
    # - gocritic
    # - gocyclo
    # - godox
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    - lll
    # - maligned
    # - misspell
    - nakedret
    # - nolintlint
    - prealloc
    - staticcheck
    # - structcheck // to be fixed by golangci-lint
    - stylecheck
    # - typecheck
    - unconvert
<<<<<<< HEAD
    # - unparam
    # - unused
    - varcheck
    # - whitespace
    # - wsl
  disable:
    - unused
    - deadcode
    - nolintlint
=======
    - unused
>>>>>>> 83b7f4ad5 (ci: Fix linter complaint (#9645))

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - linters:
        - lll
      source: "https://"
  max-same-issues: 50

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  maligned:
    suggest-new: true
  # govet:
  #   check-shadowing: true
  revive:
    min-confidence: 0
  misspell:
    locale: US
    ignore-words:
      - behaviour


