coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: 20%
    patch: off
    changes: off

github_checks:
  annotations: false

comment:
  layout: "header, diff, changes, files, footer"
  behavior: default
  require_base: no
  require_head: no

ignore:
  - "docs"
  - "DOCKER"
  - "scripts"
  - "**/*.pb.go"
  - "*.md"
  - "*.rst"
  - "*.yml"
