name: Check Code Coverage
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  test_cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            code:
              - '**/*.go'
              - 'Makefile'
              - 'tests.mk'
              - 'test/test_cover.sh'
              - 'go.*'
              - '.github/workflows/codecov.yml' # test execution

      - run: echo "GO_VERSION=$(cat .github/workflows/go-version.env | grep GO_VERSION | cut -d '=' -f2)" >> $GITHUB_ENV
        if: steps.filter.outputs.code == 'true'

      - uses: actions/setup-go@v5
        if: steps.filter.outputs.code == 'true'
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run unit tests with coverage
        if: steps.filter.outputs.code == 'true'
        run: make test_cover

      - name: Upload coverage to Codecov
        if: steps.filter.outputs.code == 'true'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
