name: Protobuf Lint
on:
  pull_request:
    paths:
      - 'proto/**'
  push:
    branches:
      - v0.38.x
    paths:
      - 'proto/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD
      - uses: bufbuild/buf-setup-action@v1.34.0
=======
      - uses: bufbuild/buf-setup-action@v1.37.0
>>>>>>> 052a8480b (build(deps): Bump bufbuild/buf-setup-action from 1.36.0 to 1.37.0 (#3749))
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'
