on:
  pull_request:
  push:
    branches:
      - main
      - release/**

name: Specs
# Runs static analysis and tests (if defined) on quint specs

jobs:
  test-specs:
    defaults:
      run:
        working-directory: spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Install quint
        run: npm install @informalsystems/quint -g
      - name: Test specs
        # --verbosity=3 shows traces explaining test failures
        run: |
          exit_code=0
          for quint_spec in **/*.qnt
          do
            quint test --verbosity=3 $quint_spec
            if [[ $? -ne 0 ]]; then
                exit_code=1
            fi
          done
          exit $exit_code
