name: Specs
# Runs static analysis and tests (if defined) on quint specs

jobs:
  test-specs:
    defaults:
      run:
        working-directory: spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: "npm"
      # --verbosity=3 shows traces explaining test failures
      - run: for quint_spec in **/*.qnt; do quint test --verbosity=3 $quint_spec; done
